import type { Rule, Finding, AnalysisContext } from "./types.js";

import {
    legacyOptionRule,
    strictRedundantRule,
    skipLibCheckRule,
    defaultRedundantRule,
    targetLibConflictRule,
    allowJsCheckRule,
    noEmitOutDirCheckRule,
    moduleResolutionMismatchRule,
    declarationNoEmitCheckRule,
    verbatimModuleIsolatedModulesRule,
    verbatimModuleSyntaxCheckRule,
    noUncheckedIndexedAccessRule,
    forceConsistentCasingInFileNamesRule,
    moduleResolutionOutdatedRule,
    emitDeclarationOnlyRule,
    legacyJsxTransformCheckRule,
    declarationMapCheckRule,
    pathsWithoutBaseUrlRule,
    outDirRootDirConflictRule,
    noEmitConflictRule,
    incrementalWithNoEmitConflictRule,
    resolveJsonModuleCheckRule,
    sourcemapConflictRule,
    isolatedDeclarationsCheckRule,
    includeExcludeOverlapRule,
    rootDirIncludeRule,
    compositeRequirementsRule,
    projectReferencesOutputRule,
    modulePackageTypeRule,
    importingTsExtensionsRule,
    performanceOptionsRule,
} from "./rules/index.js";

const rules: Rule[] = [
    legacyOptionRule,
    strictRedundantRule,
    skipLibCheckRule,
    defaultRedundantRule,
    targetLibConflictRule,
    allowJsCheckRule,
    noEmitOutDirCheckRule,
    moduleResolutionMismatchRule,
    declarationNoEmitCheckRule,
    verbatimModuleIsolatedModulesRule,
    verbatimModuleSyntaxCheckRule,
    noUncheckedIndexedAccessRule,
    forceConsistentCasingInFileNamesRule,
    moduleResolutionOutdatedRule,
    emitDeclarationOnlyRule,
    legacyJsxTransformCheckRule,
    declarationMapCheckRule,
    pathsWithoutBaseUrlRule,
    outDirRootDirConflictRule,
    noEmitConflictRule,
    incrementalWithNoEmitConflictRule,
    resolveJsonModuleCheckRule,
    sourcemapConflictRule,
    isolatedDeclarationsCheckRule,
    includeExcludeOverlapRule,
    rootDirIncludeRule,
    compositeRequirementsRule,
    projectReferencesOutputRule,
    modulePackageTypeRule,
    importingTsExtensionsRule,
    performanceOptionsRule,
];

export function analyze(config: AnalysisContext): Finding[] {
    return rules.flatMap(rule => rule.analyze(config));
}
